# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install poetry==1.5.0
      # Install docs dependencies into the same readthedocs virtualenv
      - poetry config virtualenvs.create false
      # - poetry install --no-root --only docs
      - poetry install --with docs

# Build documentation under the `docs/build` directory with Sphinx
sphinx:
  builder: html
  configuration: ci/tools/sphinx/conf.py
