## @file
# OCE Build continuous integration scripts
#
# Copyright (c) 2023, Cory Bennett. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

################################################################################

[tool.poe.tasks.bump-version]
script  = "ci.scripts.bump_version:_main"
help    = "[CI] Bumps the project version using the given semver string."

  [[tool.poe.tasks.bump-version.args]]
  name = "major"
  options = ["--major"]
  type = "boolean"
  help = "Bumps the version major."

  [[tool.poe.tasks.bump-version.args]]
  name = "minor"
  options = ["--minor"]
  type = "boolean"
  help = "Bumps the version minor."

  [[tool.poe.tasks.bump-version.args]]
  name = "patch"
  options = ["--patch"]
  type = "boolean"
  help = "Bumps the version patch."

  [[tool.poe.tasks.bump-version.args]]
  name = "pre_release"
  options = ["--pre-release"]
  type = "string"
  help = "Sets the version pre-release."

  [[tool.poe.tasks.bump-version.args]]
  name = "build"
  options = ["--build"]
  type = "boolean"
  help = "Bumps the version build."

################################################################################

[tool.poe.tasks.compare-version]
script  = "ci.scripts.compare_version:_main"
help    = "[CI] Compares a python version against a set of min/max constraints."

  [[tool.poe.tasks.compare-version.args]]
  name = "python_version"
  options = ["--version", "--python-version"]
  type = "string"
  help = "The python version to compare against (Default: system python version)"

  [[tool.poe.tasks.compare-version.args]]
  name = "min_version"
  options = ["--min", "--minimum"]
  type = "string"
  help = "The minimum python version allowed."

  [[tool.poe.tasks.compare-version.args]]
  name = "max_version"
  options = ["--max", '--maximum']
  type = "string"
  help = "The maximum python version allowed."

################################################################################

[tool.poe.tasks.resolve-modules]
script  = "ci.scripts.resolve_modules:_main"
help    = "[CI] Regenerates implicit namespace and package-level module exports."

[[tool.poe.tasks.resolve-modules.args]]
  name = "entrypoint"
  options = ["--entrypoint", "--project"]
  type = "string"
  help = "The entrypoint to resolve modules for. (Default: ocebuild entrypoint)"

################################################################################

[tool.poe.tasks.sort-imports]
script  = "ci.scripts.sort_imports:_main"
help    = "[CI] Sorts package and namespace imports in all python files."

[[tool.poe.tasks.sort-imports.args]]
  name = "entrypoint"
  options = ["--entrypoint", "--project"]
  type = "string"
  help = "The entrypoint to sort imports in. (Default: ocebuild entrypoint)"
