## @file
# Poetry plugins configuration file.
#
# Copyright (c) 2023, The OCE Build Authors. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

poethepoet = 'poethepoet[poetry_plugin]' # Run poe tasks as `poetry <task>`
